### ISSUE TITLE
please release a 1.19.2 version of this mod

### ISSUE THREAD

**Issue by Kynz0** [hlysine/create_connected#1]
I was checking out your Create: Power Loader mod and really really liked it so i thought you maybe have more mods and stummbled upon this one and honestly i love it and i really want to include it in my modpack/server called AeroSociety unfortuntely its on the minecraft version 1.19.2 (forge) so i cant add your mod so iam begging you please make the 1.19.2 version.

thank you in advance :D
<3

**Comment by hlysine** [comment]
Thanks for checking out my mods! I will publish a 1.19.2 version for this mod eventually (if everything goes well), but right now the priority is to add new features and squash bugs because the mod is still very much incomplete even in 1.20.1.

In any case, you really shouldn't use this mod in your modpacks before it reaches a stable release because things are going to break as new core features are added.
