### ISSUE TITLE
Crash when using Create Wrench on Vertical Brass Gearbox

### ISSUE THREAD

**Issue by evertn** [hlysine/create_connected#36]
Whenever the Vertical Brass Gearbox is receiving rotational power and right clicking it with the Create Wrench, the game crashes. Whenever the Vertical Brass Gearbox is not receiving any rotational power, there is no issue. Im assuming this has something to do with rotating the block while its receiving rotational power.

Minecraft version: 1.20.1
Forge: 47.2.1
Java: 17.0.8

Crashlog: [crashlog](https://mclo.gs/RMpJdRv)

**Comment by hlysine** [comment]
This crash doesn't happen during my testing, so I can only assume it is caused by one of the optimization mods you have installed which delays the update of blockstates. Please test if this dev version fixes your issue. **Pay close attention to whether the shafts of the brass gearbox are rotating in the correct direction.**
[UNZIP ME create_connected-0.6.1-dev-mc1.20.1-all.zip](https://github.com/hlysine/create_connected/files/14071023/UNZIP.ME.create_connected-0.6.1-dev-mc1.20.1-all.zip)

**Comment by evertn** [comment]
I will let you know once I had the chance to give it a try.

**Comment by evertn** [comment]
I've tested it in an offline world, and both versions do not crash with the above mentioned situation. I'll check it online with the next server update.

**Comment by evertn** [comment]
I updated the server, and the issue seems to be fixed with the dev-version.
