### ISSUE TITLE
Unable to connect to Forge servers behind Velocity proxy with Ambassador installed

### ISSUE THREAD

**Issue by HiSkyZen** [hlysine/create_connected#38]
This issue does not occur with other mods, but occurs immediately when using Create Connected mod.

It doesn't appear to be related to Velocity's forwarding mode. This happens in both Modern and Legacy forwarding.

It appears that this mod sends special characters in packets.

[Velocity Log](https://mclo.gs/NPkFV0x)
[Forge Server Log](https://mclo.gs/nBpeqKB)

Server Forge Version: 47.2.0
Server-side Mods: Create-1.20.1-0.5.1.f, Create:Connected-0.6.1-mc1.20.1, proxy-compatible-forge-1.20-1.1.4

Client Forge Version: 47.2.17
Client-side Mods: Create-1.20.1-0.5.1.f, Create:Connected-0.6.1-mc1.20.1

Velocity Version: 3.2.0-SNAPSHOT (git-07a525be-b296)
Plugin: Ambassador-1.4.3-beta

**Comment by hlysine** [comment]
[UNZIP ME create_connected-0.6.1-dev-mc1.20.1-all.zip](https://github.com/hlysine/create_connected/files/14075276/UNZIP.ME.create_connected-0.6.1-dev-mc1.20.1-all.zip)

The issue is caused by Velocity trying to enforce a strict naming rule on the network channel name. I've changed the config sync channel to use underscores instead of periods. Please test if this new version fixes your issue.

**Comment by HiSkyZen** [comment]
After testing with all conditions set the same, the problem was solved. 

I tested both Velocity's forwarding methods (Modern and Legacy).

Thank you very much!
