### ISSUE TITLE
Mod loading error has occurred

### ISSUE THREAD

**Issue by Qian-F** [hlysine/create_connected#5]
https://mclo.gs/194Vbh5

**Comment by hlysine** [comment]
This seems to be an incompatibility between C:Connected and whatever mod you have that is modifying how item durability works. 

1. Does the error persist when C:Connected is removed? If yes, then there's not much I can help. You may look into the Aether mod and see if that's the root cause.
2. If the error disappears when C:Connected is removed, please try [adding this dev version to your game](https://github.com/hlysine/create_connected/files/13761307/UNZIP.ME.create_connected-0.1.0-dev-mc1.19.2.zip) and see if it fixes the error.

**Comment by Qian-F** [comment]
> 1. Does the error persist when C:Connected is removed? If yes, then there's not much I can help. You may look into the Aether mod and see if that's the root cause.

No.

> 2. If the error disappears when C:Connected is removed, please try [adding this dev version to your game](https://github.com/hlysine/create_connected/files/13761307/UNZIP.ME.create_connected-0.1.0-dev-mc1.19.2.zip) and see if it fixes the error.


I will try it later.

**Comment by Qian-F** [comment]
Everything works well bro. This bug should be fixed!

**Comment by Qian-F** [comment]
If you release the new version, feel free to close this issue.

**Comment by hlysine** [comment]
Great! Will incorporate this fix into the next release.
