### ISSUE TITLE
Copycat blocks from "Create: Connected" crash the world when on an assembled train.

### ISSUE THREAD

**Issue by TM-yt** [hlysine/create_connected#83]
The additional Copycat Blocks break trains, to such a degree, that the world is inaccessible until the create connected is uninstalled from the mod files.

It crashes the world, and then it's impossible to re-join the world as it crashes in the same way (crash report attached)

[CrashReport.txt](https://github.com/user-attachments/files/17169194/message.txt)

**Comment by thecats1105** [comment]
same here

Create 0.5.1.h
Create: Connected 0.9.1-mc1.20.1

java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplate$StructureBlockInfo.f_74676_()" because the return value of "java.util.Map.get(Object)" is null
[Crash Log](https://pastebin.com/5T14Yjch)

**Comment by hlysine** [comment]
I cannot reproduce this crash, but I have a potential fix based on the stack trace you provided. Can you test that this build fixes your crash?

[UNZIP THIS create_connected-0.9.1-mc1.20.1-dev-all.zip](https://github.com/user-attachments/files/17324446/create_connected-0.9.1-mc1.20.1-dev-all.zip)

**Comment by TM-yt** [comment]
Like a dumbass that i am, i deleted the world that this bug happened on, I cannot recover it, and a new world doesn't bug like that, idk man....

My bad for deleting the world with the bug.

Will now be reckless in hopes of recreating the bug and then I'll see

**Comment by hlysine** [comment]
Ah in that case I think I know how the bug is triggered. Originally C:Connected 0.9.0 was incompatible with Create 0.5.1h because of a contraption fix in Create, so a fix was implemented in C:Connected 0.9.1. It seems that the fix didn't consider copycats properly, so it causes another crash if your world was corrupted by the incompatibility.

**Comment by thecats1105** [comment]
> I cannot reproduce this crash, but I have a potential fix based on the stack trace you provided. Can you test that this build fixes your crash?
> 
> [UNZIP THIS create_connected-0.9.1-mc1.20.1-dev-all.zip](https://github.com/user-attachments/files/17324446/create_connected-0.9.1-mc1.20.1-dev-all.zip)

it works
![image](https://github.com/user-attachments/assets/8cbc5168-e11c-4cbc-b14b-f4c8ac27027e)

**Comment by MagicalCodeMonkey** [comment]
I just encountered this issue last night as well. The dev build fixes ours as well!

**Comment by pstargazer** [comment]
im encountered same problem,though im using only the Copycats+ on my train, also im using horizontal fluid tank there. Is there any updates?

**Comment by thecats1105** [comment]
> im encountered same problem,though im using only the Copycats+ on my train, also im using horizontal fluid tank there. Is there any updates?

use 0.9.2
